version: '3.3'

services:
    api:
        build: src/apiService/.
        env_file: src/apiService/.env
        restart: unless-stopped
        ports:
            - "3000:3000"
        depends_on:
            - rabbitmq
            - mongo
    
    auth:
        build: src/authService/.
        env_file: src/authService/.env
        restart: unless-stopped
        ports:
            - "6200:6200"

    logger:
        build: src/loggerService/.
        env_file: src/loggerService/.env
        restart: unless-stopped
        ports:
            - "7000:7000"

    addition:
        build: src/additionService/.
        env_file: src/additionService/.env
        restart: unless-stopped
        depends_on:
            - rabbitmq

    subtraction:
        build: src/subtractionService/.
        env_file: src/subtractionService/.env
        restart: unless-stopped
        depends_on:
            - rabbitmq

    multiplication:
        build: src/multiplicationService/.
        env_file: src/multiplicationService/.env
        restart: unless-stopped
        depends_on:
            - rabbitmq

    divison:
        build: src/divisionService/.
        env_file: src/divisionService/.env
        restart: unless-stopped
        depends_on:
            - rabbitmq

    rabbitmq:
        image: 'bitnami/rabbitmq:latest'
        env_file: .env
        ports:
            - "15672:15672"
            # - "5672:5672"
        # environment:
        #     - RABBITMQ_PASSWORD=bitnami

    mongo:
        image: bitnami/mongodb:latest
        restart: unless-stopped
        # user: root
        # volumes:
        #     - /volume:/bitnami/mongodb/data